[package]
name = "rspc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.9"
tokio = { version = "1", features = ["full"]}
thiserror = "1"

[build-dependencies]
prost-build = "0.9"
